services:
  backend:
    build: app/backend
    image: ${nexus}/${docker_image_name}_backend:${BUILD_NUMBER}
    container_name: ${docker_image_name}_backend_${BUILD_NUMBER}
    labels:
      app: ${docker_image_name}
      build: ${BUILD_NUMBER}

  db:
    build: app/db
    image: ${nexus}/${docker_image_name}_db:${BUILD_NUMBER}
    container_name: ${docker_image_name}_db_${BUILD_NUMBER}
    labels:
      app: ${docker_image_name}
      build: ${BUILD_NUMBER}
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
  
  frontend:
    build: app/frontend
    image: ${nexus}/${docker_image_name}_frontend:${BUILD_NUMBER}
    container_name: ${docker_image_name}_frontend_${BUILD_NUMBER}
    labels:
      app: ${docker_image_name}
      build: ${BUILD_NUMBER}
    ports:
    - 3000:3000

secrets:
   db-password:
     file: app/db/password.txt
